"""empty message

Revision ID: 6481f0c7c406
Revises: 986ecf86a3f1
Create Date: 2021-08-28 10:36:00.987954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6481f0c7c406'
down_revision = '986ecf86a3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('child_id', sa.Integer(), nullable=True))
    op.drop_constraint('person_ibfk_3', 'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'person', ['child_id'], ['id'])
    op.drop_column('person', 'chlid_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('chlid_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key('person_ibfk_3', 'person', 'person', ['chlid_id'], ['id'])
    op.drop_column('person', 'child_id')
    # ### end Alembic commands ###
