"""empty message

Revision ID: 986ecf86a3f1
Revises: 9c88e12a11c9
Create Date: 2021-08-28 10:30:36.340430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986ecf86a3f1'
down_revision = '9c88e12a11c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('chlid_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'person', ['chlid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'chlid_id')
    # ### end Alembic commands ###
